This error related to function get_first_url of task2 file
'list' object has no attribute 'get_attribute'
###################################################################################################
This error related to function get_first_url of task2 file
'list' object has no attribute 'get_attribute'
###################################################################################################
This error related to function get_first_url of task2 file
'list' object has no attribute 'get_attribute'
###################################################################################################
This error related to function get_first_url of task2 file
list index out of range
###################################################################################################
